name: ci

on: pull_request

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run npm run fix
        run: npm run fix
      - name: Check for changes
        run: |
          git diff --exit-code || (echo "Code style error" && exit 1)
      - name: Run npm run test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          SEPOLIA_PRIVATE_KEY: ${{ secrets.SEPOLIA_PRIVATE_KEY }}
        run: npm run test
