name: ci

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run npm run fix
        run: npm run fix
      - name: Check for changes
        run: |
          git diff --exit-code || (echo "Code style error" && exit 1)
      - name: Run npm run test
        run: npm run test
